### ISSUE TITLE
Stratégie et Terme

### ISSUE THREAD

**Issue by mencattini** [cui-unige/rewriting-mencattini#1]
Hello,

Ayant relu le cours de Pr. Buchs, j'ai vu que la stratégie du _choice_ , dans son cas, demande deux `Strategy`, ainsi qu'un `Term`.
Or dans ton implémentation, il n'y a que deux `Strategy`, du coup je ne sais pas comment procéder.
J'ai implémenté qqch comme cela:
```lua
function Strategy.choice (t)
  assert (type (t) == "table")
  Fun.fromtable (t):each (function (x)
    assert (getmetatable (x) == Strategy,
            "parameters must be strategies")
  end)

  local sort = Sort "sort"
  sort.empty = {}
  sort.cons  = { sort }
  local t1 = sort.empty {}

  local res = Strategy.fail

  Fun.each(function(s)
    if s(t1) ~= nil then
      res = s
    end
  end, t)
  return res
end
```

Merci d'avance.

**Comment by saucisson** [comment]
Le paramètre `t` est une table contenant les stratégies (il peut y avoir plus que deux, on fait un choice généralisé). Le terme est lui passé lors de l'évaluation de la stratégie, comme pour `sequence`.

Regardons le code de cette dernière :

```lua
return Strategy (function (term)
    return Fun.fromtable (t):reduce (function (r, s)
      return s (r)
    end, term)
  end)
```

`Strategy.sequence` retourne une stratégie construite par une fonction prenant un terme : cette fonction décrit l'application de la stratégie `sequence` sur `term`. Ce qu'elle réalise, c'est appeler successivement toutes les sous-stratégies de la séquence sur le résultat de la précédente (ou le terme au départ), puis retourner le résultat obtenu.

**Comment by mencattini** [comment]
Je ne comprends pas.

`Choice` doit renvoyé une stratégie, et une stratégie s'applique sur un `Term`. Enfin dans le doc, je vois pas où une stratégie peut être une table.
Oui le paramètre d'entrée `t` est une table, mais le paramètre de sortie ne l'est pas. Du coup comment faire le choix?
Qu'est-ce que doit être le retour de `choice`, au niveau sémantique?
Cela doit être la stratégie qui n'est pas `fail`?

Merci d'avance

**Comment by saucisson** [comment]
La table `t` est le paramètre de choice. Dans le cours, c'est deux stratégies, ici c'est une table de stratégies, par exemple : `{ stratégie_1, stratégie_2, .. }`.

Le retour de `choice` c'est un objet `Strategy`, construit avec une fonction décrivant la sémantique de la stratégie `choice`. Cette sémantique s'applique sur un terme et applique le choice décrit dans le cours sur ce terme.

**Comment by mencattini** [comment]
J'ai résolu. 

Mais il serait bien de préciser dans la documentation que:
`Strategy` = fonction.

Je clos l'issue.
